# Generated by Django 5.1.3 on 2024-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_images_product_image_images_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1000 TO 5000', '1000 TO 5000'), ('5000 TO 10000', '5000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 35000', '20000 TO 35000'), ('35000 TO 50000', '35000 TO 50000'), ('50000 TO 100000', '50000 TO 100000')], max_length=60),
        ),
    ]
